--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HydroBoat/HYDRO-ZONE
build-by-default: true
branches:
- master
projects: [HYDRO-ZONE]
Working on MOBs!!!
Soon gonna work on Blocks/Items
...
