--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HydroBoat/HYDRO-ZONE
branches:
- master
- work-around
projects:
  HYDRO-ZONE:
    path: ""
    fullGzip: 9
    compressBuilds: false
